prefix = "."
stop-words = "stopwords.txt"

dataset = "searchapp/search/cranfield"
corpus = "searchapp/search/cranfield/line.toml"
index = "searchapp/search/idx"

query-judgements = "searchapp/search/cranfield-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "searchapp/search/cranfield-queries.txt"
query-id-start = 1