prefix = "."
stop-words = "moocs/stopwords.txt"

dataset = "moocs/moocs"
corpus = "moocs/moocs/line.toml"
index = "moocs/idx"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "moocs/mooc-queries.txt"
query-id-start = 1